### ISSUE TITLE
Ignore certain packages

### ISSUE THREAD

**Issue by zenopopovici** [AnWeber/atom-npm-outdated#1]
Hello,

It would be nice to be able to ignore some packages or ignore packages which have an url specified as version number.

We're using gulp4 and the package.json file entry looks like this:

```
"devDependencies": {
   "gulp": "github:gulpjs/gulp#4.0"
   [...]
}
```

This package will be forever "Outdated".

**Comment by AnWeber** [comment]
thanks for using my extension. Directly using a github repo in a package file is new to me. Nice to know. 
With the next release the configured version range in the package.json is validated with semver. For this type of dependency the extension only checks, if it is locally installed.

Please install the new version and test it.

**Comment by zenopopovici** [comment]
The new version doesn't work at all, although I have 2 pending updates.

**Comment by AnWeber** [comment]
Which dependencies don't get an update. I tested it with fixed Version
Range and it was working?

Zeno Popovici notifications@github.com schrieb am Do., 26. Mai 2016,
14:07:

**Comment by zenopopovici** [comment]
```
git:(develop) ✗ npm outdated
Package                Current       Wanted  Latest  Location
gulp             4.0.0-alpha.2          git     git  survey-quiz-challenge
gulp-sourcemaps    2.0.0-alpha  2.0.0-alpha   1.6.0  survey-quiz-challenge
gulp-stylus              2.3.1        2.3.1   2.4.0  survey-quiz-challenge
```

The `gulp-stylus` package was generating update notices in the last version (v4.0). Now, it's not.
